import { v } from "convex/values";
import { internalQuery, mutation, query } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import { getCurrentUser } from "./users";
import {
  detectPatterns,
  mergePatterns,
  rankPatterns,
  type PatternRecord,
} from "../lib/patterns";
import type { MutationCtx } from "./_generated/server";

/**
 * Learned preferences — the memory that belongs to the user.
 *
 * Every manual edit in the Code panel is inspected for patterns; the ones we
 * recognise are stored with a strength counter and replayed into the pipeline
 * as standing instructions. Nothing here is generated by a model, which is why
 * it can be explained to the user line by line.
 */

const MAX_TRACKED = 60;

async function loadPatterns(
  ctx: MutationCtx,
  userId: Id<"users">,
): Promise<Array<PatternRecord & { _id: Id<"userPatterns"> }>> {
  return await ctx.db
    .query("userPatterns")
    .withIndex("by_user", (q) => q.eq("userId", userId))
    .collect();
}

/**
 * Learn from one manual file edit. Called by `projectFiles.upsert`, so the
 * pattern is recorded in the same transaction that saved the user's change.
 * Returns how many new observations were recorded.
 */
export async function learnFromDiff(
  ctx: MutationCtx,
  args: {
    userId: Id<"users">;
    path: string;
    before: string;
    after: string;
  },
): Promise<number> {
  const detected = detectPatterns(args.before, args.after, args.path);
  if (detected.length === 0) return 0;

  const existing = await loadPatterns(ctx, args.userId);
  const merged = mergePatterns(
    existing.map(({ kind, statement, evidence, strength }) => ({
      kind,
      statement,
      evidence,
      strength,
    })),
    detected,
  );

  const byKind = new Map(existing.map((row) => [row.kind, row]));
  const now = Date.now();
  let added = 0;

  if (byKind.size >= MAX_TRACKED) {
    // Keep the list finite: retire the weakest preference that this edit did
    // not just reinforce.
    const stale = existing
      .filter((row) => detected.every((pattern) => pattern.kind !== row.kind))
      .sort((a, b) => a.strength - b.strength)[0];
    if (stale) {
      await ctx.db.delete(stale._id);
      byKind.delete(stale.kind);
    }
  }

  for (const pattern of merged) {
    const row = byKind.get(pattern.kind);
    if (row) {
      await ctx.db.patch(row._id, {
        statement: pattern.statement,
        evidence: pattern.evidence,
        strength: pattern.strength,
        updatedAt: now,
      });
    } else {
      await ctx.db.insert("userPatterns", {
        userId: args.userId,
        kind: pattern.kind,
        statement: pattern.statement,
        evidence: pattern.evidence,
        strength: pattern.strength,
        updatedAt: now,
      });
      added += 1;
    }
  }

  return added;
}

/** What the user (and the UI) can see: their own learned preferences. */
export const mine = query({
  args: {},
  handler: async (ctx) => {
    const user = await getCurrentUser(ctx);
    if (!user) return [];
    const rows = await ctx.db
      .query("userPatterns")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .collect();
    return rows
      .sort((a, b) => b.strength - a.strength || a.kind.localeCompare(b.kind))
      .map((row) => ({
        _id: row._id,
        kind: row.kind,
        statement: row.statement,
        evidence: row.evidence,
        strength: row.strength,
        updatedAt: row.updatedAt,
      }));
  },
});

/** Prompt feed for the generation action (internal — never sent to a client). */
export const forPrompt = internalQuery({
  args: { userId: v.id("users") },
  handler: async (ctx, { userId }) => {
    const rows = await ctx.db
      .query("userPatterns")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    return rankPatterns(
      rows.map(({ kind, statement, evidence, strength }) => ({
        kind,
        statement,
        evidence,
        strength,
      })),
    ).map(({ kind, statement, evidence, strength }) => ({
      kind,
      statement,
      evidence,
      strength,
    }));
  },
});

/** Forget one learned preference. */
export const forget = mutation({
  args: { patternId: v.id("userPatterns") },
  handler: async (ctx, { patternId }) => {
    const user = await getCurrentUser(ctx);
    if (!user) throw new Error("Not authenticated");
    const row = await ctx.db.get(patternId);
    if (!row || row.userId !== user._id) throw new Error("Запись не найдена");
    await ctx.db.delete(patternId);
  },
});

/** Forget everything the agent learned about this user. */
export const clear = mutation({
  args: {},
  handler: async (ctx) => {
    const user = await getCurrentUser(ctx);
    if (!user) throw new Error("Not authenticated");
    const rows = await ctx.db
      .query("userPatterns")
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .collect();
    for (const row of rows) await ctx.db.delete(row._id);
    return rows.length;
  },
});
